spring.application.name=route-draft
server.port=8080

# H2 콘솔 활성화
spring.h2.console.enabled=true
# H2 콘솔에 접근할 주소 경로 설정 (기본값은 /h2-console)
spring.h2.console.path=/h2-console
# 스프링 부트 3.x에서 H2 콘솔 접근 보안 필터를 허용하도록 강제하는 설정
spring.h2.console.settings.web-allow-others=true
spring.jpa.defer-datasource-initialization=true
# 데이터베이스 연결 정보 (이전 세팅과 일치하는지 확인)
spring.datasource.url=jdbc:h2:mem:routedraftdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}